<a href="https://colab.research.google.com/github/vvrgit/ML-Models-and-Applications/blob/main/K_Means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Grouping data points based on linear or non-linear equations**

In [7]:
from sklearn.cluster import KMeans

In [19]:
import numpy as np
data = np.array([[1,1,1], [0,1,1], [0,1,1], [1,1,1], [1,0,1], [0,1,1]])

In [21]:
kmeans = KMeans(n_clusters=2)

In [22]:
kmeans.fit(data)

KMeans(n_clusters=2)

In [23]:
y_cluster = kmeans.predict(data)
print(y_cluster)

[1 0 0 1 1 0]


# **Peak Load Clustering**

In [ ]:
from sklearn.cluster import KMeans

In [24]:
import pandas as pd
data=pd.read_excel("/content/Load.xlsx")

In [25]:
data.head()

Max   Min
0   10   5.0
1   12   7.0
2    8   3.0
3   14   9.0
4   16  11.0

In [45]:
from sklearn.model_selection import train_test_split
x_train,x_test=train_test_split(data,test_size=0.2,random_state=10)
print(x_train)

   Max   Min
5    6   1.0
6    5   0.8
3   14   9.0
1   12   7.0
0   10   5.0
7    4   0.6
4   16  11.0
9    2   0.5


In [46]:
kmeans = KMeans(n_clusters=2)

In [47]:
kmeans.fit(data)

KMeans(n_clusters=2)

In [49]:
y_cluster = kmeans.predict(x_train)
print(y_cluster)

[1 1 0 0 0 1 0 1]


In [50]:
print(x_test)

   Max  Min
8    3  0.7
2    8  3.0


In [51]:
y_cluster = kmeans.predict(x_test)
print(y_cluster)

[1 1]


# **EV Battery Status**

In [52]:
from sklearn.cluster import KMeans

In [53]:
import pandas as pd
data=pd.read_excel("/content/EV.xlsx")

In [54]:
data.head()

SOC   Voltage  Temperature
0  100.000000  4.019340   298.150000
1   99.760330  3.996583   298.204637
2   99.520660  3.974040   298.301235
3   99.280989  3.951894   298.439488
4   99.041319  3.930324   298.618909

In [55]:
from sklearn.model_selection import train_test_split
x_train,x_test=train_test_split(data,test_size=0.2,random_state=10)
print(x_train)

           SOC   Voltage  Temperature
81   80.586713  3.777075   312.274774
137  92.998540  0.000000   417.923029
91   78.190011  3.756939   313.685185
143  53.295317  0.000000  1056.621353
76   81.785064  3.787536   311.551274
..         ...       ...          ...
113  58.694205  3.377536   338.446582
64   84.661106  3.812598   309.758180
15   96.404947  3.896792   300.948613
125  43.700772  3.162724   355.600131
9    97.842968  3.909954   299.671488

[136 rows x 3 columns]


In [56]:
kmeans = KMeans(n_clusters=3)

In [57]:
kmeans.fit(data)

KMeans(n_clusters=3)

In [58]:
y_cluster = kmeans.predict(x_train)
print(y_cluster)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 2 0 0 0 0 1 0 1 1 0 0 2 0 0 0 2 0 1 0 0 0 2 2 0 0 0 2 0 0 0 0 0 0 0 0 0
 0 2 1 0 0 0 0 0 1 0 0 0 0 1 1 2 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 2 0 0 0 0 0 0]


In [59]:
print(x_test)

            SOC   Voltage  Temperature
52    87.537149  3.836565   307.843918
43    89.694181  3.853433   306.305228
133   37.948687  3.113465   366.337730
19    95.446266  3.891211   301.772263
67    83.942096  3.806374   310.215904
108   61.690082  3.403347   334.147213
110   60.491731  3.392864   335.867039
140   73.159129  0.000000   745.037913
10    97.603298  3.907171   299.885252
130   40.105719  3.131810   362.276158
97    76.751989  3.743841   314.512237
83    80.107372  3.772910   312.561265
105   63.487609  3.419395   331.572272
103   64.685960  3.430449   329.860029
59    85.859457  3.822788   308.978476
58    86.099128  3.824791   308.819577
161 -131.295246  0.000000  3346.771643
102   65.285136  3.436152   329.006125
49    88.256160  3.842313   307.341295
20    95.206596  3.889816   301.974338
66    84.181766  3.808453   310.064092
112   59.293380  3.382567   337.586960
111   59.892556  3.387708   336.727062
55    86.818138  3.830721   308.336586
39    90.652862  3.860386

In [60]:
y_cluster = kmeans.predict(x_test)
print(y_cluster)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]


In [65]:
soc=float(input("enter soc value"))
voltage=float(input("enter voltage value"))
Temparature=float(input("enter Temparature value"))
import numpy as np
x=np.array([[soc,voltage,Temparature]])
y_cluster = kmeans.predict(x)
print(y_cluster)

enter soc value52
enter voltage value3.5
enter Temparature value344
[0]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(
