<a href="https://colab.research.google.com/github/vvrgit/ML-Models-and-Applications/blob/main/Load_Forecasting_Polynomial_Regression_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import Libraries**

In [1]:
import numpy as np # For vector operation
import pandas as pd # For Data manipulation
import matplotlib.pyplot as plt # For plotting
import seaborn as sns #For data visualization

# **Import Data**

In [2]:
load_data=pd.read_csv("PROJECT_Final.csv")
load_data.head()

Load
0  5551.82208
1  4983.17184
2  4888.39680
3  5072.95872
4  5196.25980

# **Load Data Stat Inofrmation**

In [3]:
print(load_data.shape) # details about number of samples and features
load_data.describe()

(2184, 1)


Load
count  2184.000000
mean   6028.125312
std    1066.398766
min    3377.919600
25%    5258.767680
50%    5935.910400
75%    6738.692400
max    8841.669480

# **Data Normalization**

In [6]:
from sklearn.preprocessing import MinMaxScaler
ms=MinMaxScaler()
load_data=ms.fit_transform(load_data)
print(load_data)

[[0.39787738]
 [0.29380046]
 [0.27645431]
 ...
 [0.24629825]
 [0.32438447]
 [0.65165045]]


# **Data Pre-Processing**

In [7]:
load_data_process=np.zeros((len(load_data)-24,2))
print(load_data_process.shape)

(2160, 2)


In [8]:
k=24
for i in range(2160):
    load_data_process[i,0],load_data_process[i,1]=load_data[k-24],load_data[k]
    k=k+1
print(load_data_process)

[[0.39787738 0.28430002]
 [0.29380046 0.25579869]
 [0.27645431 0.24450087]
 ...
 [0.68414596 0.24629825]
 [0.51467861 0.32438447]
 [0.41730621 0.65165045]]


<ipython-input-8-50c524f7ddbc>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  load_data_process[i,0],load_data_process[i,1]=load_data[k-24],load_data[k]


# **Data Split**

In [11]:
dataset=pd.DataFrame(data=load_data_process[0:,0:])

In [12]:
X=dataset.iloc[:,0:1].values
Y=dataset.iloc[:,1:].values
print(Y)

[[0.28430002]
 [0.25579869]
 [0.24450087]
 ...
 [0.24629825]
 [0.32438447]
 [0.65165045]]


In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=0)
print(X_test[0:5])

[[0.65903969]
 [0.42629312]
 [0.20196285]
 [0.7751562 ]
 [0.60808536]]


# **Polynomial Features Extraction**

In [14]:
from sklearn.preprocessing import PolynomialFeatures

polynomial_features= PolynomialFeatures(degree=10)
x_poly = polynomial_features.fit_transform(X_train)

# **Polynomial Regression Model Training**

In [15]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_poly, y_train)

LinearRegression()

# **Metrics Calculation**

In [16]:
x_poly_test = polynomial_features.fit_transform(X_test)
y_poly_pred = model.predict(x_poly_test)
print(y_test[0])
print(y_poly_pred[0])

[0.54480614]
[0.62916838]


In [17]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_poly_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_poly_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_poly_pred)))

Mean Absolute Error: 0.0927449160238503
Mean Squared Error: 0.015888973506011737
Root Mean Squared Error: 0.12605147165349453


# **Model Deployment**

In [27]:
x=float(input("enter previous day load"))
xnorm=(x-3378)/(8842-3378)
xnorm=np.array(xnorm)
xnorm=xnorm.reshape(-1,1)
x_poly = polynomial_features.fit_transform(xnorm)
today_load=model.predict(x_poly)
today_load=today_load*(8842-3378)+3378
print(today_load)

enter previous day load4000
[[4607.39294434]]


In [29]:
import pickle
# Save the model
filename = 'model.pkl'
pickle.dump(model, open(filename, 'wb'))

In [32]:
x=float(input("enter previous day load"))
Load_Forecast_Model = pickle.load(open('model.pkl', 'rb'))
xnorm=(x-3378)/(8842-3378)
xnorm=np.array(xnorm)
xnorm=xnorm.reshape(-1,1)

from sklearn.preprocessing import PolynomialFeatures
polynomial_features= PolynomialFeatures(degree=10)
x_poly = polynomial_features.fit_transform(xnorm)

today_load=Load_Forecast_Model.predict(x_poly)
today_load=today_load*(8842-3378)+3378
print(today_load)

enter previous day load5000
[[5268.67360566]]
